### ISSUE TITLE
Logstash 1.5.1 : logstash can't send json that contains "lists"  to mongoDb

### ISSUE THREAD

**Issue by inptensib** [logstash-plugins/logstash-output-mongodb#9] opened 2015-06-22 14:53 UTC
Hi everybody ! I am trying to insert a json in mongoDb using Logstash-output-mongodb plugin.The json objects contain arrayLists fields so i'm getting this exception:
NoMethodError: undefined method `bson_type' for #Java::JavaUtil::ArrayList:0x745ad733,
I am using logstash 1.5.1.Thank you !!!

**Comment by purbon** [comment] 2015-09-07 12:13
@inptensib can you share your config and a dummy message to reproduce this error? on the other side, have you tried the new version? is this issue gone with it?

/Cheers

**Comment by vaidas-lungis** [comment] 2015-09-14 13:07
Exact same issue. Logstash version 1.5.4

Dummy message

```
{"message":"Request received","context":{"c":"v2","a":"index"},"level":100,"level_name":"DEBUG"}
```

conffig

```
input {
  udp {
    port => 10002
    type => "mongo"
    codec => "json"
  }
 }

output {
  # write to mongodb
  if [type] == "mongo" {
    mongodb {
      uri => "mongodb://node1,node2,node3/?replicaSet=rs0&maxPoolSize=300&w=2"
      database => "test"
      collection => "logs"
      workers => 3
      codec => "json"
    }
  }
}

```

works fine with message

```
{"message":"Request received","level":100,"level_name":"DEBUG"}
```

Without context list

**Comment by guyboertje** [comment] 2015-09-14 13:50
This is a known issue. The Ruby MongoDB client adds the `bson_xxx` methods to Ruby objects, however it does not know anything about the Java objects we get from our JSON parser.

See [logstash issue 3482](https://github.com/elastic/logstash/issues/3482)

We will probably not add these plugin specific extensions to our Java integrations in LS core.

There are two possible solutions, A) wait for JrJackson 0.3.4 to be used by LS core in 2.0, B) in this plugin convert any ArrayLists and HashMaps to their Ruby equivalents before pushing them into MongoDB.  Option B has an impact on performance.

**Comment by guyboertje** [comment] 2015-11-06 12:38
@inptensib @vaidas-lungis  - Are you able to upgrade to v1.5.5 or v2.0?

This bug should not be seen in these versions.

**Comment by svezzoli** [comment] 2015-11-24 10:56
@guyboertje 
I made a test with logstash 1.5.5 and logstash-output-mongodb -1.0.0, but this bug is still present:

{:timestamp=>"2015-11-24T11:51:58.170000+0100", :message=>"Failed to send event to MongoDB", :event=>#<LogStash::Event:0x278e55d1 @metadata={}, 

:exception=>NoMethodError: undefined method `bson_type' for "2015-11-24T10:39:26.000Z":LogStash::Timestamp>,
:backtrace=>["/application/nfmoss/vendors/logstash/vendor/bundle/jruby/1.9/gems/bson-3.2.6-java/lib/bson/hash.rb:44:in`to_bson'", "org/jruby/RubyHash.java:1342:in `each'", "/application/nfmoss/vendors/logstash/vendor/bundle/jruby/1.9/gems/bson-3.2.6-java/lib/bson/hash.rb:43:in`to_bson'", "/application/nfmoss/vendors/logstash/vendor/bundle/jruby/1.9/gems/bson-3.2.6-java/lib/bson/encodable.rb:57:in `encode_with_placeholder_and_null'", "/application/nfmoss/vendors/logstash/vendor/bundle/jruby/1.9/gems/bson-3.2.6-java/lib/bson/hash.rb:42:in`to_bson'", "/application/nfmoss/vendors/logstash/vendor/bundle/jruby/1.9/gems/bson-3.2.6-java/lib/bson/array.rb:49:in `to_bson'", "org/jruby/RubyArray.java:1613:in`each'", "org/jruby/RubyEnumerable.java:974:in `each_with_index'", "/application/nfmoss/vendors/logstash/vendor/bundle/jruby/1.9/gems/bson-3.2.6-java/lib/bson/array.rb:46:in`to_bson'", "/application/nfmoss/vendors/logstash/vendor/bundle/jruby/1.9/gems/bson-3.2.6-java/lib/bson/encodable.rb:57:in `encode_with_placeholder_and_null'", "/application/nfmoss/vendors/logstash/vendor/bundle/jruby/1.9/gems/bson-3.2.6-java/lib/bson/array.rb:45:in`to_bson'", "/application/nfmoss/vendors/logstash/vendor/bundle/jruby/1.9/gems/bson-3.2.6-java/lib/bson/hash.rb:46:in `to_bson'", "org/jruby/RubyHash.java:1342:in`each'", "/application/nfmoss/vendors/logstash/vendor/bundle/jruby/1.9/gems/bson-3.2.6-java/lib/bson/hash.rb:43:in `to_bson'", "/application/nfmoss/vendors/logstash/vendor/bundle/jruby/1.9/gems/bson-3.2.6-java/lib/bson/encodable.rb:57:in`encode_with_placeholder_and_null'", "/application/nfmoss/vendors/logstash/vendor/bundle/jruby/1.9/gems/bson-3.2.6-java/lib/bson/hash.rb:42:in `to_bson'",

**Comment by guyboertje** [comment] 2015-11-27 16:57
@svezzoli - Unfortunately, this is a similar error but not the same.  In this case it is the LS class LogStash::Timestamp that does not have a `bson_type` method.  I am unsure of how we can fix it either.

**Comment by purbon** [comment] 2015-11-30 08:08
@guyboertje @svezzoli I don't think the timestamp class should have a bson_type method, but might be this output can extend it and provide it for this plugin business. What do you think? should not be hard to archive, right?

**Comment by guyboertje** [comment] 2015-11-30 09:17
@purbon, @svezzoli - The Mongo Ruby client adds the `bson_type` and other methods to some core Ruby classes. This is very bad practice in Ruby nowadays because in creates bugs like this one.  They should have an extensible type lookup class to which we can register the `bson_type` for our custom classes.

Having said that, as you mention, a dirty hack would be to reopen the Timestamp class and add a `bson_type` method. Why dirty? Because we would have to guess the `bson_type` and the Mongo ruby client can't change it.  Also, we have to consider that there maybe a `to_bson` method missing as well.

This is fragile and makes us less free to change the Timestamp class to a JRuby extension.

**Comment by purbon** [comment] 2015-11-30 09:20
@guyboertje I agree, but what other solutions might we have for now? if `bson_type` is a required field for bson serialization in mongo we should have it, right?

**Comment by guyboertje** [comment] 2015-11-30 09:39
We don't.  I'm pointing out the pitfalls to future readers of this issue and that bugs like this are caused by decisions outside of our control.

CORRECTION - its actually the ruby-bson library that corrupts the Ruby core classes.

Maybe this is a clue to the implementation - https://github.com/mongodb/bson-ruby/blob/master/lib/bson/date_time.rb or https://github.com/mongodb/bson-ruby/blob/master/lib/bson/time.rb

Also I think we will have to do `BSON::Registry.register(BSON_TYPE, LogStash::Timestamp)` to get rid of the call to `bson_type`

**Comment by purbon** [comment] 2015-11-30 09:45
@guyboertje good catch this `ruby-bson`, makes sense to me to follow the same way as mongo does internally for the logstash timestamp.

**Comment by guyboertje** [comment] 2015-11-30 10:11
@purbon - we will need to combine the date_time and time files for our solution.  `BSON_TYPE` and Register from time and `to_bson` from date_time, calling `time` and not `to_time` in the mixin.

Also, we need to check that `@timestamp` is a legal field in Mongo and that no filters try to mutate `@timestamp` to `timestamp` because I **think** the `timestamp` field in Mongo is reserved and is a `BSON::Timestamp`, a different beast entirely.

**Comment by guyboertje** [comment] 2015-11-30 10:24
@purbon - OTOH, maybe this problem goes away of we merge https://github.com/logstash-plugins/logstash-output-mongodb/pull/1

Is `iso_date` a realistic config option and if so, should it default to true.  I am sure users will want to do date arithmetic in Mongo and a ISO8601 string is not good for that.

**Comment by ayosec** [comment] 2015-12-23 14:47
Is there any workaround for this issue? I have the problem with `Java::JavaUtil::LinkedHashMap`

**Comment by guyboertje** [comment] 2015-12-24 00:28
@ayosec - all the latest versions of LS and mongodb output should have this fixed.

You should not be seeing `Java::JavaUtil::LinkedHashMap` if you are using LS v1.5.5 or greater.

**Comment by ayosec** [comment] 2015-12-28 05:27
@guyboertje Thanks! Currently I'm using 1.5.4. I will try a newer version.

**Comment by cpiment** [comment] 2016-01-13 15:24
Hi! I'm having the issue when enabling "isodate" in the output plugin:

```
output {
  stdout { codec => rubydebug }
  mongodb {
    isodate => true
    collection => "test"
    database => "LOGSTASH"
    uri => "mongodb://hostname:port"
  }
}
```

Is there any known workaround for the issue? I'm using logstash 2.1.0 and "logstash-output-mongodb-2.0.2"

Thanks!

**Comment by guyboertje** [comment] 2016-01-14 13:03
@cpiment - what error are you seeing?

**Comment by cpiment** [comment] 2016-01-15 14:15
This one:

```
:exception=>#<NoMethodError: undefined method `bson_type' for "2016-01-13T14:17:40.000Z":LogStash::Timestamp>, :backtrace=>["/apps/elastic/base/logstash/vendor/bundle/jruby/1.9/gems/bson-3.2.6-java/lib/bson/hash.rb:44:in `to_bson'",
```

**Comment by guyboertje** [comment] 2016-01-15 16:11
@cpiment - in our tests we specifically verify this [see this line](https://github.com/logstash-plugins/logstash-output-mongodb/blob/master/spec/bson/logstash_timestamp_spec.rb#L21)

I am not sure why you are having issues.

**Comment by cpiment** [comment] 2016-01-18 11:50
@guyboertje:

I cannot find the file "logstash_timestamp_spec.rb" in my logstash installation to check if it has the same check. Where should I try to find it? I'm using the complete bundle of logstash that can be found in the elastic.io web because I work in an environment where online access from the servers is restricted.

Thanks!

**Comment by cpiment** [comment] 2016-01-20 11:01
@guyboertje I updated the plugin to the latest version with bin/plugin update logstash-output-mongodb and now it works.

Thanks for your help!

**Comment by guyboertje** [comment] 2016-01-20 13:09
@cpiment - when we 'package' logstash we remove the tests to keep the file size down.  You can see the  test in Github.

You are welcome.

I am closing this.

**Closed as completed** 2016-01-28 09:54 UTC
Labels: bug, known issue
